spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_circuitbreaker_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
            - CircuitBreaker=gateway
            - name: Retry
              args:
                retries: 2
                series: SERVER_ERROR # check
                methods: GET,POST,PUT # check
                exceptions:
                  - org.springframework.web.reactive.function.client.WebClientRequestException
                  - java.io.IOException
                backoff:
                  firstBackoff: 200ms
                  maxBackoff: 2s
                  factor: 2
                  basedOnPreviousValue: false
        - id: shopping_store_circuitbreaker_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - CircuitBreaker=gateway
        - id: warehouse_circuitbreaker_route # check
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1
            - CircuitBreaker=gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 60
        failureRateThreshold: 60
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
  instances:
    gateway:
      waitDurationInOpenState: 30000
      permittedNumberOfCallsInHalfOpenState: 5
      minimumNumberOfCalls: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true