spring:
  application:
    name: payment
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 6000
        max-attempts: 10
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/