spring:
  application:
    name: collector
  jmx:
    enabled: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: health,info

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      appache.kafka: WARN
grpc:
  server:
    port: 59091

collector:
  kafka:
    producer:
      properties:
        close-time: 15
        bootstrap.servers: localhost:9092
        client.id: "telemetry.collector"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        sensors:
          default: telemetry.sensors.v1
        hubs:
          default: telemetry.hubs.v1