spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

cloud:
  config:
    fail-fast: true
    retry:
      useRandomPolicy: true
      max-interval: 6000
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/