spring:
  application:
    name: collector
  jmx:
    enabled: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: health,info

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      appache.kafka: WARN
grpc:
  server:
    port: 59091

collector:
  kafka:
    producers:
      sensors:
        properties:
          bootstrap.servers: localhost:9092
          client.id: "telemetry.collector.sensors"
          key.serializer: org.apache.kafka.common.serialization.StringSerializer
          value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
        topics:
        - name: sensors-events
          value: telemetry.sensors.v1
      hubs:
        properties:
          bootstrap.servers: localhost:9092
          client.id: "telemetry.collector.hubs"
          key.serializer: org.apache.kafka.common.serialization.StringSerializer
          value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
        topics:
          - name: hub-events
            value: telemetry.hubs.v1
    producer:
      properties:
        close-time: 15