spring:
  application:
    name: gateway
  webflux:
    add-mappings: false
    static-path-pattern: /non-existent-path/**
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 6000
        max-attempts: 10
        useRandomPolicy: true
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10