spring:
  application:
    name: shopping-store
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: password
    password: password

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        error-decoder: ru.yandex.practicum.commerce.interactionapi.config.FeignErrorConfig
        connect-timeout: 2000
        read-timeout: 5000

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 20
      failureRateThreshold: 50
  instances:
    warehouse:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
      hibernate.SQL: TRACE
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
        web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 0

